# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7205928859e987d4a830e518ca10c553892ce03cf664ac4bedb1cddf40771bfb384a0151c7d6e877d26f4679487f0880cbb624f006fc2f0d3b037cb3f65440c4

test:
  secret_key_base: c781675cde49c02394d86d355984fc31b679185e46a797185131ec6307fd3e7f2be862a493cf6b7158d7dd8d751130296aa4876168ce3d7336abdcc6c139a5e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
